from __future__ import annotations
from pathlib import Path
from typing import Any, Dict


def _engine_forward(artifact: Path, inputs: Dict[str, Any]) -> str:
    """Run a tiny Torch forward pass.

    The artifact is expected to be a TorchScript module whose first weight
    tensor determines the required input dimension. ``inputs`` should
    contain a ``"text"`` tensor generated by :func:`puppets.text_emb`.
    """
    import torch

    module = torch.jit.load(str(artifact))
    text = inputs.get("text")
    if text is None:
        raise RuntimeError("missing text input")

    # ``nn.Linear`` style weight: ``[out_features, in_features]``.
    first_weight = next(p for p in module.parameters())
    expected_d = first_weight.shape[1]
    if text.shape[-1] != expected_d:
        raise RuntimeError(f"COND_DIM: expected {expected_d}")

    with torch.no_grad():
        module(text.reshape(-1, expected_d))
    return "ok"
