"""Command-line entry point for Reshell probing.

This module wires together the tiny planning utilities and the sandbox
to perform a single probing run.  The probing is intentionally minimal:
we iterate through candidate combinations, invoke engine helpers inside a
resource-limited subprocess, record outcomes and update our hypotheses
until one run succeeds.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Mapping, Tuple

from classifier import parse_reason

from headers import Meta, read_gguf_header, read_onnx_header, read_safetensors_header
from planner import Planner
from printers import contact_trace, obligations, proof
from puppets import latent, text_emb, vision_grid
from sandbox import spawn_sandbox


def _parse_assignments(spec: str | None) -> Dict[str, str]:
    """Parse comma-separated ``key=value`` pairs into a dict."""

    result: Dict[str, str] = {}
    if not spec:
        return result
    for part in spec.split(","):
        if "=" not in part:
            continue
        key, val = part.split("=", 1)
        result[key.strip()] = val.strip()
    return result


def _parse_guess(guess: str | None) -> Dict[str, Any]:
    """Parse ``--guess`` into hypothesis overrides."""

    mapping = {
        "d": "TEXT_EMB_d",
        "C": "LATENT_C",
        "head": "HEAD",
        "scale": "LATENT_SCALE",
        "vision": "VISION",
    }
    result: Dict[str, Any] = {}
    for key, val in _parse_assignments(guess).items():
        hyp_key = mapping.get(key, key)
        try:
            result[hyp_key] = int(val)
        except ValueError:
            result[hyp_key] = val
    return result


def _parse_limits(limits: str | None) -> Dict[str, int | float]:
    """Parse ``--limits`` into ``spawn_sandbox`` kwargs."""

    result: Dict[str, int | float] = {}
    for key, val in _parse_assignments(limits).items():
        lk = key.strip()
        lv = val.strip().lower()
        if lk == "timeout":
            if lv.endswith("s"):
                lv = lv[:-1]
            try:
                result["timeout"] = float(lv)
            except ValueError:
                pass
        elif lk in {"vram", "cpu_mem"}:
            mult = 1
            if lv.endswith("gb"):
                mult = 1024 ** 3
                lv = lv[:-2]
            elif lv.endswith("mb"):
                mult = 1024 ** 2
                lv = lv[:-2]
            try:
                result[lk] = int(float(lv) * mult)
            except ValueError:
                pass
    return result


def _read_meta(artifact: Path) -> Meta:
    """Dispatch to the appropriate header reader based on suffix."""

    suffix = artifact.suffix.lower()
    if suffix == ".safetensors":
        return read_safetensors_header(artifact)
    if suffix == ".onnx":
        return read_onnx_header(artifact)
    if suffix == ".gguf":
        return read_gguf_header(artifact)
    return Meta(tensors=[], hints={})


def _torch_engine_forward(artifact: Path, inputs: Dict[str, Any]) -> str:
    """Run a tiny Torch forward pass.

    The artifact is expected to be a TorchScript module whose first weight
    tensor determines the required input dimension.  ``inputs`` should
    contain a ``"text"`` tensor generated by :func:`puppets.text_emb`.
    """

    import torch

    module = torch.jit.load(str(artifact))
    text = inputs.get("text")
    if text is None:
        raise RuntimeError("missing text input")

    # ``nn.Linear`` style weight: ``[out_features, in_features]``.
    first_weight = next(p for p in module.parameters())
    expected_d = first_weight.shape[1]
    if text.shape[-1] != expected_d:
        raise RuntimeError(f"COND_DIM: expected {expected_d}")

    with torch.no_grad():
        module(text.reshape(-1, expected_d))
    return "ok"


def _onnx_engine_forward(artifact: Path, inputs: Dict[str, Any]) -> str:
    """Run a minimal ONNX inference step and surface failures.

    Any :mod:`onnxruntime` exception is intercepted and re-raised with
    integers extracted from the error message.  This allows the caller to
    mine hints such as expected channel counts or embedding dimensions.
    """

    import numpy as np
    import onnxruntime as ort
    import re

    sess = ort.InferenceSession(str(artifact))
    input_name = sess.get_inputs()[0].name
    expected = sess.get_inputs()[0].shape[-1]
    data = next(iter(inputs.values()))
    if hasattr(data, "numpy"):
        data = data.numpy()
    if data.shape[-1] != expected:
        raise RuntimeError(f"COND_DIM: expected {expected}")
    try:
        sess.run(None, {input_name: np.asarray(data)})
    except Exception as e:  # pragma: no cover - depends on runtime errors
        msg = str(e)
        ints = re.findall(r"\d+", msg)
        if ints:
            raise RuntimeError("ONNX_FAIL: " + " ".join(ints)) from e
        raise
    return "ok"


def _llama_engine_forward(artifact: Path, inputs: Dict[str, Any]) -> str:
    """Run a minimal llama.cpp step via :mod:`llama_cpp`.

    ``inputs`` may include optional hints (``vocab``, ``rope``, ``kv_dtype``)
    which are forwarded to the underlying :class:`llama_cpp.Llama` constructor
    when available.  A single evaluation step is then executed with the
    provided ``token_id`` (default ``0``).  Any exceptions are re-raised with
    extracted integers to aid hypothesis updates.
    """

    import re
    try:
        from llama_cpp import Llama
    except Exception as e:  # pragma: no cover - optional dependency
        raise RuntimeError("LLAMA_CPP_MISSING") from e

    token_id = int(inputs.get("token_id", 0))
    kv_dtype = inputs.get("kv_dtype")
    rope = inputs.get("rope")
    vocab = inputs.get("vocab")

    kwargs = {}
    if kv_dtype is not None:
        kwargs["f16_kv"] = kv_dtype == "f16"
    if rope is not None:
        kwargs["rope_freq_base"] = int(rope)
    if vocab is not None:
        kwargs["vocab_only"] = True

    try:
        llm = Llama(model_path=str(artifact), n_ctx=16, n_gpu_layers=0, **kwargs)
        llm.eval([token_id])  # one-step evaluation
    except Exception as e:  # pragma: no cover - runtime failure path
        msg = str(e).lower()
        ints = [int(x) for x in re.findall(r"\d+", msg)]
        if ints:
            if "vocab" in msg:
                raise RuntimeError(f"VOCAB: {max(ints)}") from e
            if "rope" in msg:
                raise RuntimeError(f"ROPE: {max(ints)}k") from e
            raise RuntimeError("LLAMA_FAIL: " + " ".join(map(str, ints))) from e
        raise
    return "ok"


def _xformers_attention_probe() -> str:
    """Attempt a tiny xFormers memory-efficient attention call.

    If xFormers is not available, the probe is silently skipped.  Any runtime
    failures include integer hints extracted from the exception message.
    """

    try:  # pragma: no cover - optional dependency
        import torch
        import xformers.ops as xops
    except Exception:
        return "skip"

    q = torch.randn(1, 2, 1, 32, dtype=torch.float16)
    k = torch.randn(1, 2, 1, 32, dtype=torch.float16)
    v = torch.randn(1, 2, 1, 32, dtype=torch.float16)

    import re

    try:
        xops.memory_efficient_attention(q, k, v)
    except Exception as e:  # pragma: no cover - layout/type mismatches
        ints = re.findall(r"\d+", str(e))
        if ints:
            raise RuntimeError("XFORMERS_FAIL: " + " ".join(ints)) from e
        raise
    return "ok"


def _probe_engine_forward(artifact: Path, inputs: Dict[str, Any]) -> str:
    """Dispatch to the appropriate engine helper and xFormers probe."""

    suffix = artifact.suffix.lower()
    if suffix == ".onnx":
        return _onnx_engine_forward(artifact, inputs)
    if suffix == ".gguf":
        return _llama_engine_forward(artifact, inputs)
    try:
        _xformers_attention_probe()
    except Exception:
        pass
    return _torch_engine_forward(artifact, inputs)


def run_pipeline(
    artifact: Path,
    out_dir: Path,
    guesses: Mapping[str, Any] | None = None,
    limits: Mapping[str, int | float] | None = None,
    fmt: str | None = None,
) -> Tuple[Path, Path, Path]:
    """Run a tiny probing loop over candidate combinations."""

    out_dir.mkdir(parents=True, exist_ok=True)
    meta = _read_meta(artifact)

    hypotheses: Dict[str, Any] = dict(meta.hints)
    if guesses:
        hypotheses.update(guesses)
    planner = Planner(seed=hypotheses)
    sandbox = spawn_sandbox(limits)

    proof_log: list[str] = []
    validation: Dict[str, Any] | None = None
    for combo in planner:
        puppet_inputs: Dict[str, Any] = {}
        if "TEXT_EMB_d" in combo:
            puppet_inputs["text"] = text_emb(combo["TEXT_EMB_d"])
        if "LATENT_C" in combo and "LATENT_SCALE" in combo:
            puppet_inputs["latent"] = latent(combo["LATENT_C"], combo["LATENT_SCALE"])
        if "VISION" in combo:
            puppet_inputs["vision"] = vision_grid(combo["VISION"])
        if "VOCAB" in combo:
            puppet_inputs["vocab"] = combo["VOCAB"]
        if "ROPE" in combo:
            puppet_inputs["rope"] = combo["ROPE"]
        if "KV_DTYPE" in combo:
            puppet_inputs["kv_dtype"] = combo["KV_DTYPE"]

        try:
            sandbox.try_forward(_probe_engine_forward, artifact, puppet_inputs)
            hypotheses.update(combo)
            proof_log.append(f"candidate {combo} -> ok")
            validation = sandbox.validate_min_run(_probe_engine_forward, artifact, puppet_inputs)
            break
        except Exception as e:  # pragma: no cover - error path
            reason = str(e)
            updates = parse_reason(reason)
            if updates:
                hypotheses.update(updates)
                planner.update(updates)
            proof_log.append(f"candidate {combo} -> {reason}")

    trace_out = contact_trace(hypotheses, validation, fmt=fmt or "json")
    oblig_out = obligations(hypotheses, fmt=fmt or "json")
    proof_out = proof(proof_log, validation, fmt=fmt or "cli")

    contact_trace_path = out_dir / "contact_trace.json"
    obligations_path = out_dir / "obligations.json"
    proof_path = out_dir / "proof.txt"
    contact_trace_path.write_text(trace_out if isinstance(trace_out, str) else json.dumps(trace_out))
    obligations_path.write_text(oblig_out if isinstance(oblig_out, str) else json.dumps(oblig_out))
    proof_path.write_text(proof_out if isinstance(proof_out, str) else json.dumps(proof_out))

    return contact_trace_path, obligations_path, proof_path


def _run(
    artifact: str,
    out_dir: str = "out",
    guess: str | None = None,
    limits: str | None = None,
    fmt: str | None = None,
) -> None:
    """Delegate to the probing pipeline.

    Parameters
    ----------
    artifact:
        Path to the model artifact to analyse.
    out_dir:
        Directory where probe results should be written.  The directory
        is created if it does not exist.
    guess:
        Optional hypothesis overrides (``key=value`` pairs).
    limits:
        Optional sandbox limits (``timeout=2s,vram=1GB``).
    fmt:
        Optional printer output format.
    """

    guesses = _parse_guess(guess)
    limits_map = _parse_limits(limits)
    contact_trace, obligations, proof_file = run_pipeline(
        Path(artifact), Path(out_dir), guesses=guesses, limits=limits_map, fmt=fmt
    )
    print(f"contact trace written to: {contact_trace}")
    print(f"obligations written to: {obligations}")
    print(f"proof transcript written to: {proof_file}")


def main() -> None:
    """Entry-point for the console script."""
    parser = argparse.ArgumentParser(description="Probe a model artifact")
    parser.add_argument("--artifact", required=True, help="path to model artifact")
    parser.add_argument("--out", default="out", help="output directory for results")
    parser.add_argument("--guess", help="seed hypotheses", default=None)
    parser.add_argument("--limits", help="resource limits", default=None)
    parser.add_argument("--format", dest="fmt", help="printer output format", default=None)
    args = parser.parse_args()

    _run(args.artifact, args.out, args.guess, args.limits, args.fmt)


if __name__ == "__main__":
    main()
