"""Command-line entry point for Reshell probing.

This module wires together the tiny planning utilities and the sandbox
to perform a single probing run.  The probing is intentionally minimal:
we iterate through candidate combinations, invoke engine helpers inside a
resource-limited subprocess, record outcomes and update our hypotheses
until one run succeeds.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Tuple

from headers import Meta, read_gguf_header, read_onnx_header, read_safetensors_header
from planner import Planner
from printers import contact_trace, obligations, proof
from puppets import latent, text_emb, vision_grid
from sandbox import spawn_sandbox


def _read_meta(artifact: Path) -> Meta:
    """Dispatch to the appropriate header reader based on suffix."""

    suffix = artifact.suffix.lower()
    if suffix == ".safetensors":
        return read_safetensors_header(artifact)
    if suffix == ".onnx":
        return read_onnx_header(artifact)
    if suffix == ".gguf":
        return read_gguf_header(artifact)
    return Meta(tensors=[], hints={})


def _torch_engine_forward(artifact: Path, inputs: Dict[str, Any]) -> str:
    """Run a tiny Torch forward pass.

    The artifact is expected to be a TorchScript module whose first weight
    tensor determines the required input dimension.  ``inputs`` should
    contain a ``"text"`` tensor generated by :func:`puppets.text_emb`.
    """

    import torch

    module = torch.jit.load(str(artifact))
    text = inputs.get("text")
    if text is None:
        raise RuntimeError("missing text input")

    # ``nn.Linear`` style weight: ``[out_features, in_features]``.
    first_weight = next(p for p in module.parameters())
    expected_d = first_weight.shape[1]
    if text.shape[-1] != expected_d:
        raise RuntimeError(f"COND_DIM: expected {expected_d}")

    with torch.no_grad():
        module(text.reshape(-1, expected_d))
    return "ok"


def _onnx_engine_forward(artifact: Path, inputs: Dict[str, Any]) -> str:
    """Run a minimal ONNX inference step and surface failures.

    Any :mod:`onnxruntime` exception is intercepted and re-raised with
    integers extracted from the error message.  This allows the caller to
    mine hints such as expected channel counts or embedding dimensions.
    """

    import numpy as np
    import onnxruntime as ort
    import re

    try:
        sess = ort.InferenceSession(str(artifact))
        input_name = sess.get_inputs()[0].name
        data = next(iter(inputs.values()))
        if hasattr(data, "numpy"):
            data = data.numpy()
        sess.run(None, {input_name: np.asarray(data)})
    except Exception as e:  # pragma: no cover - depends on runtime errors
        ints = re.findall(r"\d+", str(e))
        if ints:
            raise RuntimeError("ONNX_FAIL: " + " ".join(ints)) from e
        raise
    return "ok"


def _llama_engine_forward(artifact: Path, inputs: Dict[str, Any]) -> str:
    """Run a minimal llama.cpp step via :mod:`llama_cpp`.

    The model's metadata is read when instantiating :class:`llama_cpp.Llama`.
    We then perform a single evaluation step with a provided ``token_id``
    (default ``0``).  Any exceptions are re-raised with extracted integers to
    aid hypothesis updates.
    """

    import re
    try:
        from llama_cpp import Llama
    except Exception as e:  # pragma: no cover - optional dependency
        raise RuntimeError("LLAMA_CPP_MISSING") from e

    token_id = int(inputs.get("token_id", 0))
    try:
        llm = Llama(model_path=str(artifact), n_ctx=16, n_gpu_layers=0)
        llm.eval([token_id])  # one-step evaluation
    except Exception as e:  # pragma: no cover - runtime failure path
        ints = re.findall(r"\d+", str(e))
        if ints:
            raise RuntimeError("LLAMA_FAIL: " + " ".join(ints)) from e
        raise
    return "ok"


def _xformers_attention_probe() -> str:
    """Attempt a tiny xFormers memory-efficient attention call.

    If xFormers is not available, the probe is silently skipped.  Any runtime
    failures include integer hints extracted from the exception message.
    """

    try:  # pragma: no cover - optional dependency
        import torch
        import xformers.ops as xops
    except Exception:
        return "skip"

    q = torch.randn(1, 2, 1, 32, dtype=torch.float16)
    k = torch.randn(1, 2, 1, 32, dtype=torch.float16)
    v = torch.randn(1, 2, 1, 32, dtype=torch.float16)

    import re

    try:
        xops.memory_efficient_attention(q, k, v)
    except Exception as e:  # pragma: no cover - layout/type mismatches
        ints = re.findall(r"\d+", str(e))
        if ints:
            raise RuntimeError("XFORMERS_FAIL: " + " ".join(ints)) from e
        raise
    return "ok"


def _probe_engine_forward(artifact: Path, inputs: Dict[str, Any]) -> str:
    """Dispatch to the appropriate engine helper and xFormers probe."""

    suffix = artifact.suffix.lower()
    if suffix == ".onnx":
        return _onnx_engine_forward(artifact, inputs)
    if suffix == ".gguf":
        return _llama_engine_forward(artifact, inputs)
    try:
        _xformers_attention_probe()
    except Exception:
        pass
    return _torch_engine_forward(artifact, inputs)


def _parse_reason(msg: str) -> Dict[str, Any]:
    """Extract hypothesis updates from ``msg`` if possible."""
    # Errors may be wrapped like ``RuntimeError('COND_DIM: expected 4')`` –
    # peel off the wrapper if present.
    if "'" in msg:
        msg = msg.split("'", 2)[1]
    parts = msg.split()
    if msg.startswith("COND_DIM") and parts[-1].isdigit():
        return {"TEXT_EMB_d": int(parts[-1])}
    if msg.startswith("LATENT_C") and parts[-1].isdigit():
        return {"LATENT_C": int(parts[-1])}
    return {}


def run_pipeline(artifact: Path, out_dir: Path) -> Tuple[Path, Path, Path]:
    """Run a tiny probing loop over candidate combinations."""

    out_dir.mkdir(parents=True, exist_ok=True)
    meta = _read_meta(artifact)

    hypotheses: Dict[str, Any] = {}
    planner = Planner(seed=hypotheses)
    sandbox = spawn_sandbox({"timeout": 2.0})

    proof_log: list[str] = []
    for combo in planner:
        puppet_inputs: Dict[str, Any] = {}
        if "TEXT_EMB_d" in combo:
            puppet_inputs["text"] = text_emb(combo["TEXT_EMB_d"])
        if "LATENT_C" in combo and "LATENT_SCALE" in combo:
            puppet_inputs["latent"] = latent(combo["LATENT_C"], combo["LATENT_SCALE"])
        if "VISION" in combo:
            puppet_inputs["vision"] = vision_grid(combo["VISION"])

        try:
            sandbox.try_forward(_probe_engine_forward, artifact, puppet_inputs)
            hypotheses.update(combo)
            proof_log.append(f"candidate {combo} -> ok")
            break
        except Exception as e:  # pragma: no cover - error path
            reason = str(e)
            updates = _parse_reason(reason)
            if updates:
                hypotheses.update(updates)
            proof_log.append(f"candidate {combo} -> {reason}")

    trace_json = contact_trace(hypotheses, fmt="json")
    oblig_json = obligations(hypotheses, fmt="json")
    proof_text = proof(proof_log, fmt="cli")

    contact_trace_path = out_dir / "contact_trace.json"
    obligations_path = out_dir / "obligations.json"
    proof_path = out_dir / "proof.txt"
    contact_trace_path.write_text(json.dumps(trace_json))
    obligations_path.write_text(json.dumps(oblig_json))
    proof_path.write_text(proof_text)

    return contact_trace_path, obligations_path, proof_path


def _run(artifact: str, out_dir: str = "out") -> None:
    """Delegate to the probing pipeline.

    Parameters
    ----------
    artifact:
        Path to the model artifact to analyse.
    out_dir:
        Directory where probe results should be written.  The directory
        is created if it does not exist.
    """
    contact_trace, obligations, proof_file = run_pipeline(Path(artifact), Path(out_dir))
    print(f"contact trace written to: {contact_trace}")
    print(f"obligations written to: {obligations}")
    print(f"proof transcript written to: {proof_file}")


def main() -> None:
    """Entry-point for the console script."""
    parser = argparse.ArgumentParser(description="Probe a model artifact")
    parser.add_argument("--artifact", required=True, help="path to model artifact")
    parser.add_argument("--out", default="out", help="output directory for results")
    args = parser.parse_args()

    _run(args.artifact, args.out)


if __name__ == "__main__":
    main()
